### ISSUE TITLE
Workflow output 

### ISSUE THREAD

**Issue by politicus** [Luzifer/alfred-fold#1]
This is the kind of workflow I was looking for a long time. 

The problem I have is that I want to be able to do the following. If I copy "1234567890" to the clipboard and I fold this piece of content with a width value of 2 I still will get one clip (composed of 12, 34, 56, 78, 90). I would like to get 5 clips of two numbers. 

Is it possible ?

I tried to fold a selection of 5 urls and it is working pretty well. The only problem I have is that the output is composed of 5 urls not 5 clips of one url.

**Comment by Luzifer** [comment]
If you have the clipboard history feature enabled theoretically it would be possible by splitting the text and calling `pbcopy` multiple times. But as the intention of this workflow is just to reformat the copied text I'm not going to implement this feature…
